#!/bin/bash

# Function to check if a number is prime
is_prime() {
    num=$1
    if [ $num -lt 2 ]; then
        return 1
    fi
    for ((i = 2; i <= $num / 2; i++)); do
        if [ $((num % i)) -eq 0 ]; then
            return 1
        fi
    done
    return 0
}

# Loop through numbers from 1 to 100 and display primes
for ((num = 2; num <= 100; num++)); do
    if is_prime "$num"; then
        echo "$num"
    fi
done

Output :
Prime numbers from 1 to 100:
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
